package com.rncsjad.constant;

public enum RewardAdEvent {
  ON_ERROR,
  ON_REWARD_VIDEO_AD_LOAD,
  ON_REWARD_VIDEO_CACHED,

  ON_AD_SHOW,
  ON_AD_VIDEO_BAR_CLICK,
  ON_AD_CLOSE,
  ON_VIDEO_COMPLETE,
  ON_VIDEO_ERROR,
  ON_SKIPPED_VIDEO,
  ON_REWARD_ARRIVED,

  ON_AD_SHOW_PLAY_AGAIN,
  ON_AD_VIDEO_BAR_CLICK_PLAY_AGAIN,
  ON_AD_CLOSE_PLAY_AGAIN,
  ON_VIDEO_COMPLETE_PLAY_AGAIN,
  ON_VIDEO_ERROR_PLAY_AGAIN,
  ON_SKIPPED_VIDEO_PLAY_AGAIN,
  ON_REWARD_ARRIVED_PLAY_AGAIN;
  ;
}
